// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qzsvxbftzrqpwyklumun.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6c3Z4YmZ0enJxcHd5a2x1bXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzMTAzMTUsImV4cCI6MjA0Nzg4NjMxNX0.SEmLi4_VgWAvEfWR6C75e4w6pl3AFJ1tE8jZtxE5LXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);